spring:
  application:
    name: ecommerce-spring-boot
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: true
          autoregister_listeners: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-millis: ${JWT_EXPIRATION_MILLIS:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
