package com.smart.ecommerce.report.dto;
import com.smart.ecommerce.enums.InventoryMovementType;import com.smart.ecommerce.report.util.ReportGranularity;import java.math.*;import java.time.*;import java.util.*;
public final class InventoryReportDtos{private InventoryReportDtos(){}
 public enum StockStatus{IN_STOCK,LOW_STOCK,OUT_OF_STOCK} public enum MovementDirection{INCREASE,DECREASE,ZERO} public enum ReconciliationStatus{MATCHED,MISMATCHED,NO_HISTORY,INVALID_HISTORY} public enum AdjustmentSortBy{ADJUSTMENT_COUNT,ABSOLUTE_QUANTITY_CHANGED,NET_ADJUSTMENT}
 public record CurrentInventoryRow(Long productId,String productName,String sku,Long categoryId,String categoryName,boolean active,int currentStock,int lowStockThreshold,StockStatus stockStatus,BigDecimal unitCost,BigDecimal currentStockValue,BigDecimal sellingPrice,BigDecimal potentialRetailValue,BigDecimal averageRating,long reviewsCount,Instant lastInventoryMovementAt){}
 public record LowStockRow(Long productId,String productName,String categoryName,int currentStock,int threshold,int shortageQuantity,Instant lastSoldAt,Instant lastRestockedAt,long totalSoldInSelectedPeriod,BigDecimal averageDailySales,BigDecimal estimatedDaysRemaining){}
 public record OutOfStockRow(Long productId,String productName,String categoryName,int currentStock,Instant lastSoldAt,Instant lastInventoryMovementAt,long totalHistoricalQuantitySold,Instant dateBecameOutOfStock,BigDecimal averageRating,long reviewsCount){}
 public record ValuationCategoryTotal(Long categoryId,String categoryName,long totalProducts,long totalUnitsInStock,BigDecimal totalStockCostValue,BigDecimal totalPotentialRetailValue,BigDecimal potentialGrossMarginValue){}
 public record ValuationRow(Long productId,String productName,String categoryName,int currentStock,BigDecimal unitCost,BigDecimal sellingPrice,BigDecimal stockCostValue,BigDecimal retailValue,BigDecimal potentialGrossMargin,BigDecimal marginPercentage){}
 public record ValuationResponse(long totalProducts,long totalUnitsInStock,BigDecimal totalStockCostValue,BigDecimal totalPotentialRetailValue,BigDecimal potentialGrossMarginValue,String currency,List<ValuationCategoryTotal> totalsByCategory,com.smart.ecommerce.dto.PaginationResponse<ValuationRow> rows,String limitation){}
 public record MovementRow(Long movementId,Long productId,String productName,String categoryName,InventoryMovementType movementType,int quantityBefore,int quantityChange,int quantityAfter,MovementDirection direction,Long orderId,String orderNumber,Long customerId,String customerNameSnapshot,Long performedByUserId,String performedByName,String note,Instant createdAt){}
 public record MovementSummaryResponse(long totalMovements,long totalQuantityIncreased,long totalQuantityDecreased,long netQuantityChange,Map<InventoryMovementType,Long> movementsByType,long productsAffected,long uniqueOrdersAffected,long uniqueCustomersAffected){}
 public record LedgerMovementRow(Instant createdAt,InventoryMovementType movementType,String reference,int quantityBefore,int quantityChange,int quantityAfter,String performedBy,String note){}
 public record ProductInventoryLedgerResponse(Long productId,String productName,String sku,String categoryName,int currentStock,Integer openingBalance,Integer closingBalance,long totalIncreases,long totalDecreases,long netMovement,com.smart.ecommerce.dto.PaginationResponse<LedgerMovementRow> movements){}
 public record NeverSoldRow(Long productId,String productName,String categoryName,int currentStock,Instant createdAt,long daysSinceCreation,BigDecimal sellingPrice,BigDecimal stockValue,Instant lastInventoryMovementAt){}
 public record MostAdjustedRow(Long productId,String productName,long adjustmentCount,long totalQuantityIncreased,long totalQuantityDecreased,long netAdjustment,Instant lastAdjustmentAt,int currentStock){}
 public record RestorationRow(Long productId,String productName,InventoryMovementType movementType,String orderNumber,String customerNameSnapshot,int quantityRestored,String performedBy,String reason,Instant createdAt){}
 public record RestorationResponse(long totalRestorationMovements,long totalUnitsRestored,long cancelledOrderUnitsRestored,long returnedProductUnitsRestored,com.smart.ecommerce.dto.PaginationResponse<RestorationRow> rows){}
 public record ReconciliationRow(Long productId,String productName,int storedCurrentStock,Integer derivedCurrentStock,Integer difference,ReconciliationStatus reconciliationStatus,Instant lastMovementAt){}
 public record ReconciliationResponse(long totalProductsChecked,long matchedProducts,long mismatchedProducts,long productsWithoutHistory,long totalAbsoluteDifference,List<ReconciliationRow> rows){}
 public record InventoryTrendPoint(Instant periodStart,String label,long quantityIncreased,long quantityDecreased,long netQuantityChange,long movementCount){}
 public record InventoryTrendResponse(LocalDate dateFrom,LocalDate dateTo,ReportGranularity granularity,List<InventoryTrendPoint> points){}
 public record TurnoverResponse(LocalDate dateFrom,LocalDate dateTo,Long productId,Long categoryId,long unitsSold,BigDecimal averageUnitsOnHand,BigDecimal stockTurnoverByUnits,BigDecimal estimatedDaysOfInventory,String limitation){}
}
