package com.smart.ecommerce.report.generator.pdf;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.smart.ecommerce.report.dto.InventoryReportDtos.*;
import com.smart.ecommerce.report.service.ReportProperties;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.List;
import org.springframework.core.io.*;
import org.springframework.stereotype.Component;
@Component
public class PdfInventoryReportGenerator {
  private final ReportProperties props;
  private final ResourceLoader loader;
  public PdfInventoryReportGenerator(ReportProperties props,
                                     ResourceLoader loader) {
    this.props = props;
    this.loader = loader;
  }
  public byte[] table(String title, String[] h, List<String[]> rows,
                      List<String> summary, Locale l, String by, String zone) {
    try {
      ByteArrayOutputStream out = new ByteArrayOutputStream();
      Document d = new Document(PageSize.A4.rotate(), 36, 36, 54, 54);
      PdfWriter w = PdfWriter.getInstance(d, out);
      d.open();
      Font n = font(false), b = font(true);
      d.add(new Paragraph(props.companyName() + "\n" + title, b));
      d.add(new Paragraph("Generated by: " + by + " Timezone: " + zone, n));
      for (String s : summary)
        d.add(new Paragraph(s, n));
      PdfPTable t = new PdfPTable(h.length);
      t.setWidthPercentage(100);
      t.setRunDirection(l != null && "ar".equals(l.getLanguage())
                            ? PdfWriter.RUN_DIRECTION_RTL
                            : PdfWriter.RUN_DIRECTION_LTR);
      for (String x : h) {
        PdfPCell c = new PdfPCell(new Phrase(x, b));
        c.setBackgroundColor(java.awt.Color.LIGHT_GRAY);
        t.addCell(c);
      }
      t.setHeaderRows(1);
      for (String[] r : rows)
        for (String x : r)
          t.addCell(new Phrase(x == null ? "" : x, n));
      d.add(t);
      d.close();
      return out.toByteArray();
    } catch (Exception e) {
      throw new IllegalStateException("report.error.pdf_generation_failed", e);
    }
  }
  public byte[] current(List<CurrentInventoryRow> rows, Locale l, String by,
                        String z) {
    return table(
        "Current Inventory",
        new String[] {"Product", "Category", "Status", "Stock", "Threshold",
                      "Unit Cost", "Stock Value", "Selling Price",
                      "Retail Value"},
        rows.stream()
            .map(x
                 -> new String[] {x.productName(), x.categoryName(),
                                  String.valueOf(x.stockStatus()),
                                  "" + x.currentStock(),
                                  "" + x.lowStockThreshold(), v(x.unitCost()),
                                  v(x.currentStockValue()), v(x.sellingPrice()),
                                  v(x.potentialRetailValue())})
            .toList(),
        List.of("Unit cost unavailable when product cost is not modeled."), l,
        by, z);
  }
  public byte[] low(List<LowStockRow> rows, Locale l, String by, String z) {
    return table(
        "Low Stock",
        new String[] {"Product", "Category", "Current Stock", "Threshold",
                      "Shortage", "Average Daily Sales",
                      "Estimated Days Remaining"},
        rows.stream()
            .map(x
                 -> new String[] {
                     x.productName(), x.categoryName(), "" + x.currentStock(),
                     "" + x.threshold(), "" + x.shortageQuantity(),
                     v(x.averageDailySales()), v(x.estimatedDaysRemaining())})
            .toList(),
        List.of(), l, by, z);
  }
  public byte[] movements(List<MovementRow> rows, Locale l, String by,
                          String z) {
    return table(
        "Inventory Movements",
        new String[] {"Date", "Product", "Movement Type", "Before", "Change",
                      "After", "Order Number", "Performed By"},
        rows.stream()
            .map(x
                 -> new String[] {
                     String.valueOf(x.createdAt()), x.productName(),
                     String.valueOf(x.movementType()), "" + x.quantityBefore(),
                     "" + x.quantityChange(), "" + x.quantityAfter(),
                     x.orderNumber(), x.performedByName()})
            .toList(),
        List.of(), l, by, z);
  }
  public byte[] reconciliation(List<ReconciliationRow> rows, Locale l,
                               String by, String z) {
    return table(
        "Inventory Reconciliation",
        new String[] {"Product", "Stored Stock", "Derived Stock", "Difference",
                      "Status", "Last Movement"},
        rows.stream()
            .map(x
                 -> new String[] {x.productName(), "" + x.storedCurrentStock(),
                                  String.valueOf(x.derivedCurrentStock()),
                                  String.valueOf(x.difference()),
                                  String.valueOf(x.reconciliationStatus()),
                                  String.valueOf(x.lastMovementAt())})
            .toList(),
        List.of(), l, by, z);
  }
  private String v(Object o) { return o == null ? "" : String.valueOf(o); }
  private Font font(boolean bold) throws Exception {
    String p = props.pdf().regularFont();
    Resource r = loader.getResource(p);
    BaseFont bf;
    if (p.endsWith(".base64")) {
      byte[] bytes = Base64.getMimeDecoder().decode(new String(
          r.getInputStream().readAllBytes(), StandardCharsets.US_ASCII));
      bf = BaseFont.createFont("embedded-report-font.ttf", BaseFont.IDENTITY_H,
                               BaseFont.EMBEDDED, false, bytes, null);
    } else
      bf = BaseFont.createFont(r.getURL().toString(), BaseFont.IDENTITY_H,
                               BaseFont.EMBEDDED);
    return new Font(bf, bold ? 11 : 9, bold ? Font.BOLD : Font.NORMAL);
  }
}
