package com.smart.ecommerce.report.repository;
import com.smart.ecommerce.entity.Order;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.repository.*;import org.springframework.data.repository.query.Param;
public interface SalesReportRepository extends JpaRepository<Order,Long>{
 @Query("""select coalesce(sum(o.totalAmount),0) totalRevenue,count(o) completedOrders,coalesce(sum(o.totalItems),0) totalItemsSold,count(distinct o.customer.id) uniqueCustomers,coalesce(max(o.totalAmount),0) highestOrderValue,coalesce(min(o.totalAmount),0) lowestOrderValue from Order o where o.status=com.smart.ecommerce.enums.OrderStatus.COMPLETED and coalesce(o.completedAt,o.createdAt)>=:from and coalesce(o.completedAt,o.createdAt)<:to and (:currency is null or o.currency=:currency)""") SummaryProjection summary(Instant from,Instant to,String currency);
 @Query("""select count(distinct o.customer.id) from Order o where o.status=com.smart.ecommerce.enums.OrderStatus.COMPLETED and coalesce(o.completedAt,o.createdAt)>=:from and coalesce(o.completedAt,o.createdAt)<:to and not exists(select 1 from Order p where p.customer.id=o.customer.id and p.status=com.smart.ecommerce.enums.OrderStatus.COMPLETED and coalesce(p.completedAt,p.createdAt)<:from)""") long newCustomers(Instant from,Instant to);
 @Query("""select o.status as status,count(o) as total from Order o where o.createdAt>=:from and o.createdAt<:to group by o.status""") List<StatusProjection> statusSummary(Instant from,Instant to);
 @Query("""select o.id orderId,o.orderNumber orderNumber,c.id customerId,concat(c.firstName,' ',c.lastName) customerName,o.totalAmount totalAmount,o.currency currency,count(oi.id) itemsCount,coalesce(sum(oi.quantity),0) totalQuantity,coalesce(o.completedAt,o.createdAt) completedAt,o.createdAt createdAt,d.id deliveryUserId,concat(d.firstName,' ',d.lastName) deliveryUserName from Order o join o.customer c left join o.assignedDeliveryUser d join o.items oi left join Product p on p.id=oi.productId where o.status=com.smart.ecommerce.enums.OrderStatus.COMPLETED and coalesce(o.completedAt,o.createdAt)>=:from and coalesce(o.completedAt,o.createdAt)<:to and (:orderNumber is null or lower(o.orderNumber) like lower(concat('%',:orderNumber,'%'))) and (:customerId is null or c.id=:customerId) and (:customerName is null or lower(concat(c.firstName,' ',c.lastName)) like lower(concat('%',:customerName,'%'))) and (:minAmount is null or o.totalAmount>=:minAmount) and (:maxAmount is null or o.totalAmount<=:maxAmount) and (:productId is null or oi.productId=:productId) and (:categoryId is null or p.category.id=:categoryId) and (:deliveryId is null or d.id=:deliveryId) and (:currency is null or o.currency=:currency) group by o.id,o.orderNumber,c.id,c.firstName,c.lastName,o.totalAmount,o.currency,o.completedAt,o.createdAt,d.id,d.firstName,d.lastName""") Page<OrderRowProjection> orderRows(Instant from,Instant to,String orderNumber,Long customerId,String customerName,BigDecimal minAmount,BigDecimal maxAmount,Long productId,Long categoryId,Long deliveryId,String currency,Pageable pageable);
 @Query("""select oi.productId productId,oi.productName productName,p.sku sku,p.category.id categoryId,coalesce(p.category.nameEn,'Historical/Deleted') categoryName,coalesce(sum(oi.quantity),0) quantitySold,count(distinct o.id) ordersCount,coalesce(sum(oi.lineTotal),0) revenue,coalesce(p.stockQuantity,0) currentStock,coalesce(p.averageRating,0) averageRating,coalesce(p.reviewsCount,0) reviewsCount from OrderItem oi join oi.order o left join Product p on p.id=oi.productId where o.status=com.smart.ecommerce.enums.OrderStatus.COMPLETED and coalesce(o.completedAt,o.createdAt)>=:from and coalesce(o.completedAt,o.createdAt)<:to group by oi.productId,oi.productName,p.sku,p.category.id,p.category.nameEn,p.stockQuantity,p.averageRating,p.reviewsCount""") List<TopProductProjection> topProducts(Instant from,Instant to,Pageable pageable);
 @Query("""select p.category.id categoryId,coalesce(p.category.nameEn,'Historical/Deleted') categoryName,count(distinct oi.productId) productsSold,coalesce(sum(oi.quantity),0) quantitySold,count(distinct o.id) completedOrders,coalesce(sum(oi.lineTotal),0) revenue,count(oi.id) itemRows from OrderItem oi join oi.order o left join Product p on p.id=oi.productId where o.status=com.smart.ecommerce.enums.OrderStatus.COMPLETED and coalesce(o.completedAt,o.createdAt)>=:from and coalesce(o.completedAt,o.createdAt)<:to group by p.category.id,p.category.nameEn""") Page<CategoryProjection> categories(Instant from,Instant to,Pageable pageable);
 @Query("""select c.id customerId,concat(c.firstName,' ',c.lastName) customerName,count(o) completedOrders,coalesce(sum(o.totalItems),0) itemsPurchased,coalesce(sum(o.totalAmount),0) totalSpent,min(coalesce(o.completedAt,o.createdAt)) firstCompletedOrderAt,max(coalesce(o.completedAt,o.createdAt)) lastCompletedOrderAt from Order o join o.customer c where o.status=com.smart.ecommerce.enums.OrderStatus.COMPLETED and coalesce(o.completedAt,o.createdAt)>=:from and coalesce(o.completedAt,o.createdAt)<:to and (:customerId is null or c.id=:customerId) and (:customerName is null or lower(concat(c.firstName,' ',c.lastName)) like lower(concat('%',:customerName,'%'))) group by c.id,c.firstName,c.lastName""") Page<CustomerProjection> customers(Instant from,Instant to,Long customerId,String customerName,Pageable pageable);
 @Query("""select count(p)>0 from Product p where p.id=:id""") boolean productExists(Long id);
 @Query("""select p.id productId,p.nameEn productName,p.sku sku,p.category.id categoryId,p.category.nameEn categoryName,p.stockQuantity currentStock,p.averageRating averageRating,p.reviewsCount reviewsCount from Product p where p.id=:id""") ProductInfoProjection productInfo(Long id);
 @Query("""select o.orderNumber orderNumber,concat(c.firstName,' ',c.lastName) customerName,coalesce(o.completedAt,o.createdAt) completedAt,oi.quantity quantity,oi.unitPrice unitPrice,oi.lineTotal lineTotal,oi.currency currency from OrderItem oi join oi.order o join o.customer c where o.status=com.smart.ecommerce.enums.OrderStatus.COMPLETED and oi.productId=:productId and coalesce(o.completedAt,o.createdAt)>=:from and coalesce(o.completedAt,o.createdAt)<:to order by coalesce(o.completedAt,o.createdAt) desc""") List<RecentItemProjection> recentItems(Long productId,Instant from,Instant to,Pageable pageable);
 interface SummaryProjection{BigDecimal getTotalRevenue();long getCompletedOrders();long getTotalItemsSold();long getUniqueCustomers();BigDecimal getHighestOrderValue();BigDecimal getLowestOrderValue();}
 interface StatusProjection{com.smart.ecommerce.enums.OrderStatus getStatus();long getTotal();}
 interface OrderRowProjection{Long getOrderId();String getOrderNumber();Long getCustomerId();String getCustomerName();BigDecimal getTotalAmount();String getCurrency();long getItemsCount();long getTotalQuantity();Instant getCompletedAt();Instant getCreatedAt();Long getDeliveryUserId();String getDeliveryUserName();}
 interface TopProductProjection{Long getProductId();String getProductName();String getSku();Long getCategoryId();String getCategoryName();long getQuantitySold();long getOrdersCount();BigDecimal getRevenue();int getCurrentStock();BigDecimal getAverageRating();long getReviewsCount();}
 interface CategoryProjection{Long getCategoryId();String getCategoryName();long getProductsSold();long getQuantitySold();long getCompletedOrders();BigDecimal getRevenue();long getItemRows();}
 interface CustomerProjection{Long getCustomerId();String getCustomerName();long getCompletedOrders();long getItemsPurchased();BigDecimal getTotalSpent();Instant getFirstCompletedOrderAt();Instant getLastCompletedOrderAt();}
 interface ProductInfoProjection{Long getProductId();String getProductName();String getSku();Long getCategoryId();String getCategoryName();int getCurrentStock();BigDecimal getAverageRating();long getReviewsCount();}
 interface RecentItemProjection{String getOrderNumber();String getCustomerName();Instant getCompletedAt();int getQuantity();BigDecimal getUnitPrice();BigDecimal getLineTotal();String getCurrency();}
}
