package com.smart.ecommerce.service;

import com.smart.ecommerce.dto.PaginationResponse;
import com.smart.ecommerce.dto.order.OrderDtos.*;
import com.smart.ecommerce.entity.*;
import com.smart.ecommerce.enums.*;
import com.smart.ecommerce.exception.ResourceNotFoundException;
import com.smart.ecommerce.repository.*;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service @RequiredArgsConstructor
public class OrderService {
 private final CustomerContextService ctx; private final CartRepository carts; private final CartItemRepository cartItems; private final ProductRepository products; private final CustomerAddressRepository addresses; private final OrderRepository orders; private final OrderStatusHistoryRepository histories; private final OrderNumberGenerator numbers; private final OrderCalculationService calc; private final OrderStatusTransitionService transitions; private final OrderMapper mapper;
 @Transactional public OrderResponse create(CreateOrderRequest r){ User u=ctx.currentCustomer(); Cart cart=carts.lockByCustomerIdAndStatus(u.getId(),CartStatus.ACTIVE).orElseThrow(()->new IllegalArgumentException("Cart is empty")); if(cart.getItems().isEmpty()) throw new IllegalArgumentException("Cart is empty"); CustomerAddress a=addresses.findById(r.addressId()).orElseThrow(()->new ResourceNotFoundException("Address not found")); if(!a.isActive()) throw new IllegalArgumentException("Address is inactive"); if(!a.getCustomer().getId().equals(u.getId())) throw new ResourceNotFoundException("Address not found"); List<Long> ids=cart.getItems().stream().map(i->i.getProduct().getId()).distinct().sorted().toList(); Map<Long,Product> locked=products.lockWithImagesByIdIn(ids).stream().collect(Collectors.toMap(Product::getId,Function.identity())); if(locked.size()!=ids.size()) throw new ResourceNotFoundException("Product not found"); Order o=new Order(); o.setOrderNumber(numbers.generate()); o.setCustomer(u); o.setStatus(OrderStatus.PENDING); o.setCustomerNotes(r.customerNotes()); snapshotAddress(o,a); BigDecimal subtotal=BigDecimal.ZERO.setScale(3); int totalItems=0; String currency=null; for(CartItem ci:cart.getItems()){ Product p=locked.get(ci.getProduct().getId()); validateProduct(p,ci.getQuantity()); String c=CurrencyCode.defaultIfBlank(p.getCurrency()); if(currency==null) currency=c; else if(!currency.equals(c)) throw new IllegalArgumentException("Mixed currencies in cart are not supported"); BigDecimal unit=calc.money(effectivePrice(p)); BigDecimal line=calc.line(unit,ci.getQuantity()); p.setStockQuantity(p.getStockQuantity()-ci.getQuantity()); OrderItem item=new OrderItem(); item.setOrder(o); item.setProductId(p.getId()); item.setProductName(p.getNameEn()); item.setProductImageUrl(primary(p)); item.setQuantity(ci.getQuantity()); item.setUnitPrice(unit); item.setCurrency(c); item.setLineTotal(line); o.getItems().add(item); subtotal=subtotal.add(line); totalItems+=ci.getQuantity(); }
 if(!CurrencyCode.DEFAULT_CURRENCY.equals(currency)) throw new IllegalArgumentException("Unsupported currency: "+currency); o.setCurrency(currency); o.setSubtotal(calc.money(subtotal)); o.setDeliveryFee(calc.deliveryFee()); o.setDiscountAmount(calc.discount()); o.setTotalAmount(calc.money(o.getSubtotal().add(o.getDeliveryFee()).subtract(o.getDiscountAmount()))); o.setTotalItems(totalItems); addHistory(o,null,OrderStatus.PENDING,u,"CUSTOMER",null); Order saved=orders.save(o); cartItems.deleteByCartId(cart.getId()); return mapper.toResponse(saved); }
 @Transactional(readOnly=true) public PaginationResponse<OrderSummaryResponse> customerList(OrderStatus status, Pageable pageable){ User u=ctx.currentCustomer(); Pageable p=newest(pageable); Page<Order> page=status==null?orders.findByCustomerId(u.getId(),p):orders.findByCustomerIdAndStatus(u.getId(),status,p); return PaginationResponse.from(page.map(mapper::toSummary)); }
 @Transactional(readOnly=true) public OrderResponse customerGet(Long id){ User u=ctx.currentCustomer(); return mapper.toResponse(orders.findByIdAndCustomerId(id,u.getId()).orElseThrow(()->new ResourceNotFoundException("Order not found"))); }
 @Transactional(readOnly=true) public OrderResponse customerGetNumber(String n){ User u=ctx.currentCustomer(); return mapper.toResponse(orders.findByOrderNumberAndCustomerId(n,u.getId()).orElseThrow(()->new ResourceNotFoundException("Order not found"))); }
 @Transactional public OrderResponse customerCancel(Long id, CancelOrderRequest r){ User u=ctx.currentCustomer(); Order o=orders.lockWithItemsById(id).orElseThrow(()->new ResourceNotFoundException("Order not found")); if(!o.getCustomer().getId().equals(u.getId())) throw new ResourceNotFoundException("Order not found"); return cancel(o,r.reason(),u,"CUSTOMER",false); }
 @Transactional(readOnly=true) public List<OrderStatusHistoryResponse> customerHistory(Long id){ User u=ctx.currentCustomer(); Order o=orders.findById(id).orElseThrow(()->new ResourceNotFoundException("Order not found")); if(!o.getCustomer().getId().equals(u.getId())) throw new ResourceNotFoundException("Order not found"); return histories.findByOrderIdOrderByChangedAtAsc(id).stream().map(mapper::toHistory).toList(); }
 @Transactional(readOnly=true) public PaginationResponse<OrderSummaryResponse> adminList(OrderStatus status,String num,String customer,Instant from,Instant to,Pageable pageable){ return PaginationResponse.from(orders.searchAdmin(status,blank(num),blank(customer),from,to,newest(pageable)).map(mapper::toSummary)); }
 @Transactional(readOnly=true) public OrderResponse adminGet(Long id){ return mapper.toResponse(orders.findById(id).orElseThrow(()->new ResourceNotFoundException("Order not found"))); }
 @Transactional(readOnly=true) public OrderResponse adminGetNumber(String n){ return mapper.toResponse(orders.findByOrderNumber(n).orElseThrow(()->new ResourceNotFoundException("Order not found"))); }
 @Transactional public OrderResponse adminStatus(Long id, UpdateOrderStatusRequest r){ User u=ctx.currentCustomer(); Order o=orders.lockWithItemsById(id).orElseThrow(()->new ResourceNotFoundException("Order not found")); transitions.validate(o.getStatus(),r.status()); OrderStatus prev=o.getStatus(); o.setStatus(r.status()); if(r.status()==OrderStatus.COMPLETED) o.setCompletedAt(Instant.now()); addHistory(o,prev,r.status(),u,"ADMIN",r.note()); return mapper.toResponse(o); }
 @Transactional public OrderResponse adminCancel(Long id, CancelOrderRequest r){ User u=ctx.currentCustomer(); Order o=orders.lockWithItemsById(id).orElseThrow(()->new ResourceNotFoundException("Order not found")); return cancel(o,r.reason(),u,"ADMIN",true); }
 @Transactional(readOnly=true) public List<OrderStatusHistoryResponse> adminHistory(Long id){ if(!orders.existsById(id)) throw new ResourceNotFoundException("Order not found"); return histories.findByOrderIdOrderByChangedAtAsc(id).stream().map(mapper::toHistory).toList(); }
 private OrderResponse cancel(Order o,String reason,User u,String role,boolean admin){ if(o.getStatus()==OrderStatus.CANCELLED) return mapper.toResponse(o); if(o.getStatus()==OrderStatus.COMPLETED) throw new IllegalArgumentException("Order already completed"); if(admin?!transitions.canAdminCancel(o.getStatus()):!transitions.canCustomerCancel(o.getStatus())) throw new IllegalArgumentException("Order cannot be cancelled"); restore(o); OrderStatus prev=o.getStatus(); o.setStatus(OrderStatus.CANCELLED); o.setCancellationReason(reason); o.setCancelledAt(Instant.now()); addHistory(o,prev,OrderStatus.CANCELLED,u,role,reason); return mapper.toResponse(o); }
 private void restore(Order o){ List<Long> ids=o.getItems().stream().map(OrderItem::getProductId).distinct().sorted().toList(); Map<Long,Product> ps=products.lockWithImagesByIdIn(ids).stream().collect(Collectors.toMap(Product::getId,Function.identity())); for(OrderItem i:o.getItems()){ Product p=ps.get(i.getProductId()); if(p!=null) p.setStockQuantity(p.getStockQuantity()+i.getQuantity()); }}
 private void validateProduct(Product p,int q){ if(p.isDeleted()) throw new ResourceNotFoundException("Product not found"); if(!p.isActive()) throw new IllegalArgumentException("Product is inactive"); if(p.getStockQuantity()<=0) throw new IllegalArgumentException("Product is unavailable"); if(p.getStockQuantity()<q) throw new IllegalArgumentException("Insufficient stock"); if(effectivePrice(p)==null||effectivePrice(p).compareTo(BigDecimal.ZERO)<0) throw new IllegalArgumentException("Invalid product price"); }
 private BigDecimal effectivePrice(Product p){ return p.getDiscountPrice()==null?p.getPrice():p.getDiscountPrice(); } private String primary(Product p){ return p.getImages().stream().filter(ProductImage::isPrimaryImage).findFirst().or(()->p.getImages().stream().findFirst()).map(ProductImage::getImageUrl).orElse(null); }
 private void snapshotAddress(Order o,CustomerAddress a){ o.setRecipientName(a.getRecipientName());o.setPhoneNumber(a.getPhoneNumber());o.setCity(a.getCity());o.setLatitude(a.getLatitude());o.setLongitude(a.getLongitude());o.setArea(a.getArea());o.setStreet(a.getStreet());o.setAdditionalDirections(a.getAdditionalDirections()); }
 private void addHistory(Order o,OrderStatus prev,OrderStatus next,User u,String role,String note){ OrderStatusHistory h=new OrderStatusHistory(); h.setOrder(o);h.setPreviousStatus(prev);h.setNewStatus(next);h.setChangedByUserId(u.getId());h.setChangedByRole(role);h.setNote(note);h.setChangedAt(Instant.now());o.getStatusHistory().add(h); }
 private Pageable newest(Pageable p){ return PageRequest.of(p.getPageNumber(),p.getPageSize(),Sort.by(Sort.Direction.DESC,"createdAt")); } private String blank(String s){ return s==null||s.isBlank()?null:s; }
}
