package com.smart.ecommerce.report.controller;
import com.smart.ecommerce.enums.InventoryMovementType;import com.smart.ecommerce.report.dto.InventoryFilters.*;import com.smart.ecommerce.report.dto.InventoryReportDtos.*;import com.smart.ecommerce.report.dto.ReportDtos.ExportedReport;import com.smart.ecommerce.report.service.InventoryReportExportService;import com.smart.ecommerce.report.util.ReportPeriod;import io.swagger.v3.oas.annotations.tags.Tag;import java.math.BigDecimal;import java.time.LocalDate;import java.util.Locale;import lombok.RequiredArgsConstructor;import org.springframework.context.i18n.LocaleContextHolder;import org.springframework.core.io.ByteArrayResource;import org.springframework.data.domain.Pageable;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequiredArgsConstructor @RequestMapping("/api/v1/admin/reports/inventory") @Tag(name="Admin Inventory PDF Export") @PreAuthorize("hasRole('ADMIN')")
public class InventoryExportController{private final InventoryReportExportService service;
 @GetMapping(value="/current/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> current(@RequestParam(required=false) Long productId,@RequestParam(required=false) String productName,@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Boolean active,@RequestParam(required=false) StockStatus stockStatus,@RequestParam(required=false) Integer minStock,@RequestParam(required=false) Integer maxStock,@RequestParam(required=false) BigDecimal minUnitCost,@RequestParam(required=false) BigDecimal maxUnitCost){return pdf(service.current(new Current(productId,productName,categoryId,active,stockStatus,minStock,maxStock,minUnitCost,maxUnitCost),loc()));}
 @GetMapping(value="/low-stock/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> low(@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Integer threshold,@RequestParam(required=false) Boolean active,@RequestParam(defaultValue="TODAY") ReportPeriod period,@RequestParam(required=false) LocalDate dateFrom,@RequestParam(required=false) LocalDate dateTo){return pdf(service.low(categoryId,threshold,active,new Period(period,dateFrom,dateTo),loc()));}
 @GetMapping(value="/out-of-stock/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> out(@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Boolean active){return pdf(service.out(categoryId,active,loc()));}
 @GetMapping(value="/valuation/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> valuation(@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Boolean active,@RequestParam(required=false) StockStatus stockStatus){return pdf(service.valuation(categoryId,active,stockStatus,loc()));}
 @GetMapping(value="/movements/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> movements(@RequestParam(required=false) Long productId,@RequestParam(required=false) Long categoryId,@RequestParam(required=false) InventoryMovementType movementType,@RequestParam(required=false) String orderNumber,@RequestParam(required=false) Long customerId,@RequestParam(required=false) Long performedByUserId,@RequestParam(defaultValue="TODAY") ReportPeriod period,@RequestParam(required=false) LocalDate dateFrom,@RequestParam(required=false) LocalDate dateTo,@RequestParam(required=false) Integer minQuantityChange,@RequestParam(required=false) Integer maxQuantityChange,@RequestParam(required=false) MovementDirection direction){return pdf(service.movements(new Movement(productId,categoryId,movementType,orderNumber,customerId,performedByUserId,period,dateFrom,dateTo,minQuantityChange,maxQuantityChange,direction),loc()));}
 @GetMapping(value="/products/{productId}/ledger/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> ledger(@PathVariable Long productId,@RequestParam(defaultValue="TODAY") ReportPeriod period,@RequestParam(required=false) LocalDate dateFrom,@RequestParam(required=false) LocalDate dateTo){return pdf(service.ledger(productId,new Period(period,dateFrom,dateTo),loc()));}
 @GetMapping(value="/never-sold/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> never(@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Boolean active,@RequestParam(required=false) LocalDate createdBefore){return pdf(service.neverSold(categoryId,active,createdBefore,loc()));}
 @GetMapping(value="/most-adjusted/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> adjusted(@RequestParam(defaultValue="TODAY") ReportPeriod period,@RequestParam(required=false) LocalDate dateFrom,@RequestParam(required=false) LocalDate dateTo,@RequestParam(defaultValue="100") int limit,@RequestParam(defaultValue="ADJUSTMENT_COUNT") String sortBy){return pdf(service.adjusted(new Period(period,dateFrom,dateTo),limit,sortBy,loc()));}
 @GetMapping(value="/restorations/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> restorations(@RequestParam(defaultValue="TODAY") ReportPeriod period,@RequestParam(required=false) LocalDate dateFrom,@RequestParam(required=false) LocalDate dateTo,@RequestParam(required=false) InventoryMovementType movementType){return pdf(service.restorations(new Period(period,dateFrom,dateTo),movementType,loc()));}
 @GetMapping(value="/reconciliation/export/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<ByteArrayResource> reconciliation(@RequestParam(defaultValue="false") boolean onlyMismatched){return pdf(service.reconciliation(onlyMismatched,loc()));}
 private Locale loc(){return LocaleContextHolder.getLocale();} private ResponseEntity<ByteArrayResource> pdf(ExportedReport r){return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+r.filename()+"\"").body(new ByteArrayResource(r.content()));}}
