package com.smart.ecommerce.report.service;
import com.smart.ecommerce.dto.PaginationResponse;import com.smart.ecommerce.report.dto.*;import com.smart.ecommerce.report.dto.ReportDtos.*;import com.smart.ecommerce.report.generator.pdf.PdfSalesReportGenerator;import com.smart.ecommerce.report.util.ReportPeriod;import java.time.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.stereotype.Service;
@Service public class ReportExportService{private final SalesReportService sales;private final DateRangeResolver ranges;private final ReportProperties props;private final PdfSalesReportGenerator pdf;public ReportExportService(SalesReportService sales,DateRangeResolver ranges,ReportProperties props,PdfSalesReportGenerator pdf){this.sales=sales;this.ranges=ranges;this.props=props;this.pdf=pdf;}
 public ExportedReport salesPdf(SalesOrderFilter f,Locale l){checkRange(f.period(),f.dateFrom(),f.dateTo());var summary=sales.summary(f.period(),f.dateFrom(),f.dateTo());var rows=sales.orders(f,PageRequest.of(0,props.maxPdfRows()+1,Sort.by(Sort.Direction.DESC,"completedAt")));checkRows(rows.totalElements());return new ExportedReport(name("sales-report",summary.dateFrom(),summary.dateTo()),pdf.sales(summary,rows,l,user(),zone(f.period(),f.dateFrom(),f.dateTo())),rows.content().size());}
 public ExportedReport topProductsPdf(ReportPeriod p,LocalDate f,LocalDate t,Integer limit,String sort,Locale l){checkRange(p,f,t);var rows=sales.topProducts(p,f,t,limit==null?100:Math.min(limit,props.maxPdfRows()+1),sort);checkRows(rows.size());var r=ranges.resolve(p,f,t);return new ExportedReport(name("top-products-report",r.dateFrom(),r.dateTo()),pdf.topProducts(rows,l,user(),r.zoneId().toString()),rows.size());}
 public ExportedReport categoriesPdf(ReportPeriod p,LocalDate f,LocalDate t,Pageable pg,Locale l){checkRange(p,f,t);var rows=sales.categories(p,f,t,PageRequest.of(0,props.maxPdfRows()+1,pg.getSort()));checkRows(rows.totalElements());var r=ranges.resolve(p,f,t);return new ExportedReport(name("category-sales-report",r.dateFrom(),r.dateTo()),pdf.categories(rows,l,user(),r.zoneId().toString()),rows.content().size());}
 public ExportedReport customersPdf(CustomerSalesFilter f,Pageable pg,Locale l){checkRange(f.period(),f.dateFrom(),f.dateTo());var rows=sales.customers(f,PageRequest.of(0,props.maxPdfRows()+1,pg.getSort()));checkRows(rows.totalElements());var r=ranges.resolve(f.period(),f.dateFrom(),f.dateTo());return new ExportedReport(name("customer-sales-report",r.dateFrom(),r.dateTo()),pdf.customers(rows,l,user(),r.zoneId().toString()),rows.content().size());}
 private void checkRange(ReportPeriod p,LocalDate f,LocalDate t){var r=ranges.resolve(p,f,t);if(r.daysInclusive()>props.maxExportRangeDays())throw new IllegalArgumentException("report.error.range_too_large");} private void checkRows(long n){if(n>props.maxPdfRows())throw new IllegalArgumentException("report.error.pdf_row_limit_exceeded");}
 private String name(String prefix,LocalDate f,LocalDate t){return (prefix+"-"+f+"-to-"+t+".pdf").replaceAll("[^A-Za-z0-9._-]","-");} private String user(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?"system":a.getName();} private String zone(ReportPeriod p,LocalDate f,LocalDate t){return ranges.resolve(p,f,t).zoneId().toString();}
}
