CREATE TABLE website_settings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    settings_key VARCHAR(40) NOT NULL DEFAULT 'default',
    company_name VARCHAR(200),
    company_description_en VARCHAR(2000),
    company_description_ar VARCHAR(2000),
    company_logo_url VARCHAR(1000),
    company_logo_storage_path VARCHAR(1000),
    owner_name_en VARCHAR(200),
    owner_name_ar VARCHAR(200),
    owner_image_url VARCHAR(1000),
    owner_image_storage_path VARCHAR(1000),
    location_url VARCHAR(1000),
    location_name VARCHAR(300),
    instagram_url VARCHAR(1000),
    facebook_url VARCHAR(1000),
    tiktok_url VARCHAR(1000),
    linkedin_url VARCHAR(1000),
    company_active BOOLEAN NOT NULL DEFAULT TRUE,
    contact_email VARCHAR(254),
    contact_phone VARCHAR(30),
    contact_address_en VARCHAR(500),
    contact_address_ar VARCHAR(500),
    contact_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_website_settings_key UNIQUE (settings_key)
);
