package com.smart.ecommerce.enums;

public enum InventoryMovementType {
  PRODUCT_CREATED,
  PRODUCT_UPDATED,
  ORDER_CREATED,
  ORDER_CANCELLED,
  ORDER_STATUS_ADJUSTMENT,
  ADMIN_ADJUSTMENT,
  PRODUCT_RETURNED
}
